### ISSUE TITLE
Consider adding Sponsor button to this repository

### ISSUE THREAD

**Issue by S0AndS0** [hasadna/sensory-interface#116]
GitHub allows for adding a Sponsor button to repositories via a [`github/FUNDING.yml`](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) file, one of the services that are supported is [LiberaPay](https://liberapay.com/about/faq) which if I remember correctly does **not** have any fees. Adding the following file to this repository after enabling GitHub Sponsorship may make it easier for clients to directly support this project.

**`github/FUNDING.yml`**

```yml
liberapay: sensory-interface
```

**Comment by oferb** [comment]
Done!
Thanks, great idea.
