### ISSUE TITLE
Consider using OscillatorNode.Type

### ISSUE THREAD

**Issue by oferb** [hasadna/sensory-interface#17]
As suggested by @S0AndS0:
https://developer.mozilla.org/en-US/docs/Web/API/OscillatorNode/type

This would probably go in `createAndSetOscillator()`:
https://github.com/hasadna/sensory-interface/blob/master/ts/view/audio.ts#L28-L45

It might sound better using a different type.

**Comment by mohammad-suliman** [comment]
Thanks @S0AndS0 as always for the suggestion!
We changed our approach by using a library for playing tones in #50. So I think this is somewhat outdated now. Suggestions now for improving the audio experience should be based on the library we are using now. I am closing for this reason, feel free to reopen if you don't agree.
