### ISSUE TITLE
Consider automated tests and builds

### ISSUE THREAD

**Issue by S0AndS0** [hasadna/sensory-interface#20]
The [Jest](https://jestjs.io/) testing framework may help prevent some bugs from ever entering the code of this repository; though I think there are other options available too.

Both [Travis CI](https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle) and [GitHub Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/getting-started-with-github-actions) are solid choices for automating testing as well as build processes. Personally I find Travis CI to be the easier option for testing, and GH Actions _should_ be relativity simple to automate builds once tests return bug free.

Additionally if the build process were to either output to a _`build`_ branch or build from a _`source`_ branch, it may make things easier for those wishing to incorporate code within their own sites. For example if TypeScript where to be moved to a _`source`_ branch and the compiled files where to remain in the `master` branch, those utilizing GitHub Pages built with Jekyll could include code as a [Git Submodule](https://help.github.com/en/github/working-with-github-pages/using-submodules-with-github-pages)...

```Bash
mkdir -p ~/git/hub/org/site
cd ~/git/hub/org/site
git init .

git checkout -b gh-pages

mkdir -p assets/js/modules

git submodule add\
 -b master\
 --name sensory-interface https://github.com/hasadna/sensory-interface.git\
 assets/js/modules/sensory-interface
```

... at which point code from this repository may be accessed by _`org/site`_, all without losing the option to update, version lock, and review changes.

**Comment by oferb** [comment]
S0AndS0 - as we're having some discussions on this through chat, let's update it after the discussions.

**Comment by oferb** [comment]
Closed for cleaning up the list, but is still considered for future development.
