### ISSUE TITLE
Consider adding loadable configurations

### ISSUE THREAD

**Issue by S0AndS0** [hasadna/sensory-interface#22]
I've been doing some tests with [GitHub Pages](https://s0ands0.github.io/sensory-interface/) as a hosting option, however, it seems the `updateURL` function within the `public/app.js` file will need updated such that [`newUrl += '/view/index.html?';`](https://github.com/hasadna/sensory-interface/blob/master/public/app.js#L21) path can be modified.

I think I've found one way of allowing for this project to have a configuration file, that is also able to be modified at the time of sourcing. Here's a _sketch_ of some of the things I'm thinking...

**`index.html`**

```HTML
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body onload="">
    <script type="text/javascript" src="assets/js/index.js?json_path=assets/js/config.json">
    </script>
  </body>
</html>
```

**`config.json`** _or_ **`assets/js/config.json`**

```JSON
{
  "foo": "bar",
  "list": [
    "of",
    "values",
    "and",
    "stuff"
  ]
}
```

**`assets/js/index.js`**

```JavaScript
let default_json_path = 'config.json';


const get_json_path = () => {
  const scripts = document.getElementsByTagName('script');
  const this_src = scripts[scripts.length - 1].src;
  const src_params = new URLSearchParams(this_src.split('?')[1]);
  const json_path = src_params.get('json_path');
  if (json_path) {
    return json_path;
  }
  return default_json_path;
};


window.addEventListener('load', (_event) => {
  const json_path = get_json_path();

  const xhr = new XMLHttpRequest();
  xhr.onload = () => {
    if (xhr.readyState !== 4 && xhr.status !== 200) {
      console.error(xhr.statusText);
    }
    const json_results = JSON.parse(xhr.responseText);
    console.log('--- json_results ---');
    console.log(json_results);
    console.log(`json_results['foo'] -> ${json_results['foo']}`);
  };

  xhr.ontimeout = () => {
    console.error(`Request for ${path} timed out`);
  };

  xhr.open("GET", json_path, true);
  xhr.send(null);

});
```

If the `?json_path=assets/js/config.json` URL search parameter is not present then JavaScript _should_ default to reading from `config.json`, and in either case that should allow for modifying behavior.

___

> Resources that where helpful with bodging above together

- https://gist.github.com/willurd/5720255

- https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event

- https://stackoverflow.com/questions/40667307/possible-to-get-query-parameters-of-the-script-src-javascript-url

- https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/onreadystatechange

- https://stackoverflow.com/questions/37217658/return-value-from-onreadystatechange-with-callback

- https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests

- https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest

**Comment by oferb** [comment]
S0AndS0 - as we're having some discussions on this through chat, let's update it after the discussions.

**Comment by oferb** [comment]
Hey, can you explain what are these configuration files, and also, what is "time of sourcing"?
😀

**Comment by S0AndS0** [comment]
The configuration files could eventually contain things like default text-to-speak speed, voice, etc. it could be a way for anyone utilizing this project on other sites to further customize things.

As for "time of sourcing", I'm referring to when a browser reads a `src` tag, which is not necessarily within the same interval as when script is executed.

**Comment by oferb** [comment]
The way we currently control these types of configurations is through the UI, which in turn runs some javascript. So if another website would want to use it, they could run similar javascript to set these configs.

**Comment by oferb** [comment]
Closed for cleaning up the list, but is still considered for future development.
