### ISSUE TITLE
Better CSV support

### ISSUE THREAD

**Issue by oferb** [hasadna/sensory-interface#23]
Supporting more types of CSVs, using some standard battle-tested library. We rolled our own, but we only support tabs, not commas, and of course none of the edge-cases. No need to reinvent the wheel here, so using some existing library would be great.

**Comment by S0AndS0** [comment]
A quick search for CSV parser in either Rust or JavaScript returned the following results...


- https://docs.rs/csv/1.0.0-beta.5/csv/tutorial/index.html

- https://github.com/BurntSushi/rust-csv

- https://stackoverflow.com/questions/1293147/javascript-code-to-parse-csv-data#10290562

- https://github.com/okfn/csv.js/


... for _quick-&-dirty_ development I think that StackOverflow options will be the easiest to implement. The Rust based approaches will likely be the most performant when combined with WebAssembly, but may be a _bit_ much at this stage. And for NPM based solutions I'm not thrilled by the idea of shipping more external dependencies.

**Comment by oferb** [comment]
Great!!
I say let's go with one of the simpler options using js libraries.
Wanna take this on?

**Comment by S0AndS0** [comment]
Groovy, perhaps once I'm done un-breaking what I've been doing on the Fork I'm testing with. So no need to wait on me if this is an important feature.

**Comment by oferb** [comment]
Ok

**Comment by mohammad-suliman** [comment]
Thanks @S0AndS0  for your suggestions and collaboration!
We in fact have addressed that by #42 , so closing...
