### ISSUE TITLE
Website visual design

### ISSUE THREAD

**Issue by oferb** [hasadna/sensory-interface#29]
The website looks really bad (hey, at least I'm honest) visually. We didn't invest in it, but, for sighted people it's good to have something that looks nice. We already have a visual design, but it needs to be implemented. It's just a design for a single page, the main landing page for the project.

Note that right now, we have only 3 pages, so no need for extra tools (e.g Jekyll).

**Comment by oferb** [comment]
This is the design:
![image](https://user-images.githubusercontent.com/5137671/74029754-11d0e600-49b6-11ea-9571-4d50bfd06ec7.png)

**Comment by mohammad-suliman** [comment]
@oferb, does this issue relate to the hole site? Or for the landing page only? I am asking to know whether to close this, or to keep open.
Thanks!

**Comment by oferb** [comment]
Just landing page.
