### ISSUE TITLE
Consider Hilbert curve to map image based graphs to sound

### ISSUE THREAD

**Issue by S0AndS0** [hasadna/sensory-interface#68]
Main benefit is that increasing the _resolution_ doesn't adversely effect the _positions_ of mapped sounds, the video from 3Blue1Brown on YouTube...

https://www.youtube.com/watch?v=3s7h2MHQtxc

... has some excellent examples of why this is method is better than simple _scan-line_ based methods I was pondering.

The Math StackExchange Q&A has succinct equations that may be translated to {Type/Java}Script...

https://math.stackexchange.com/questions/921985/what-is-the-hilbert-curves-equation

There are some preexisting projects on GitHub that may provide some inspiration...

https://github.com/topics/hilbert-curve?l=javascript

And Wikipedia has further information...

https://en.wikipedia.org/wiki/Hilbert_curve

**Comment by oferb** [comment]
Hey, indeed an enhancement. We'll first focus on getting a basic working version first.

**Comment by S0AndS0** [comment]
I totally agree; mainly I shared this because it seemed like a near perfect fit for translating image based graphs to sound, while also eliminating problems of changes of scaling causing pixels to move along translated frequencies.

**Comment by oferb** [comment]
Closing this as I referenced it in another issue and I'd like to clear it from the list.
