### ISSUE TITLE
Create a stock market page

### ISSUE THREAD

**Issue by oferb** [hasadna/sensory-interface#95]

**Comment by oferb** [comment]
Here's a free API:
https://financialmodelingprep.com/developer/docs/#Stock-Historical-Price

Example:
https://financialmodelingprep.com/api/company/historical-price/bud?serietype=line&serieformat=array&datatype=json

https://jsfiddle.net/Financialmodelingprep/ypfbrjs8/?utm_source=website&utm_medium=embed&utm_campaign=ypfbrjs8

**Comment by oferb** [comment]
@BitanTomer Wanna make a page to view historical stock prices?

It'll be the most accessible on the internet probably :)

**Comment by BitanTomer** [comment]
@oferb Great, I'll work on it later this week, I will contact you for more details.

**Comment by oferb** [comment]
This is done!
